kind: project
metadata:
  name: new-git-project
spec:
  functions: []
  workflows: []
  artifacts: []
  source: git://github.com/mlrun/mlrun.git#refs/heads/master
  origin_url: git://github.com/mlrun/mlrun.git#refs/heads/master
  desired_state: online
